name: C++ CI/CD with Docker and Tag Release

on:
  push:
    # Trigger only on cpp-docker branch and tags starting with v
    branches:
      - "cpp-docker"
    tags:
      - "v*"   # Trigger release for any semantic version tag like v0.1, v1.0

permissions:
  contents: write

jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build Docker image (Dockerfile should run tests)
      - name: Build & Run Tests
        run: docker build -t cpp-app-ci -f Dockerfile .

  release:
    needs: build-test
    runs-on: ubuntu-22.04
    if: success() && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up C++ build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Build release binary using CMake
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          # Copy binary to root for release
          cp my_app ../my_app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_app-linux-x86_64
          path: ./my_app

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ./my_app
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
